MetaDataFormat = "yaml"
theme = "solstice"
languageCode = "en-us"
title = "Common Build Infrastructure"

canonifyurls = true

[params]
  description = "Common Build Infrastructure Website"
  author = "Mikaël Barbero"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Hudson for Eclipse Projects"
  pre = ""
  url = "/build/hudson"
  parent = "Build"
